import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav style={{ width: "100%", padding: "16px 0", background: "#f3f3f3", borderBottom: "1px solid #eee", marginBottom: 24 }}>
          <div style={{ maxWidth: 900, margin: "0 auto", display: "flex", gap: 32 }}>
            <Link href="/" style={{ fontWeight: "bold", color: "#333", textDecoration: "none" }}>Inicio</Link>
              <Link href="/productos" style={{ color: "#333", textDecoration: "none" }}>Productos</Link>
            <a href="/contacto" style={{ color: "#333", textDecoration: "none" }}>Contacto</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
